// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZMKU-S-H0cUeyyTja86cBaVHKdoxlFU',
    appId: '1:942040795881:web:35bde2c7d26a0a9fedbe78',
    messagingSenderId: '942040795881',
    projectId: 'legaleasier-15871',
    authDomain: 'legaleasier-15871.firebaseapp.com',
    storageBucket: 'legaleasier-15871.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09d3fvP4GxMr0SC-MVRfF5ZF47EZLWtg',
    appId: '1:942040795881:android:2994a5709c34f0b1edbe78',
    messagingSenderId: '942040795881',
    projectId: 'legaleasier-15871',
    storageBucket: 'legaleasier-15871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fwqlZyhJMCJizM1k_GdJq9AZbLDt1vY',
    appId: '1:942040795881:ios:a5ec4bf4860da405edbe78',
    messagingSenderId: '942040795881',
    projectId: 'legaleasier-15871',
    storageBucket: 'legaleasier-15871.firebasestorage.app',
    iosClientId: '942040795881-c54og28abm4vr5stfe7mui9vsc9ufpqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.legaleasier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fwqlZyhJMCJizM1k_GdJq9AZbLDt1vY',
    appId: '1:942040795881:ios:a5ec4bf4860da405edbe78',
    messagingSenderId: '942040795881',
    projectId: 'legaleasier-15871',
    storageBucket: 'legaleasier-15871.firebasestorage.app',
    iosClientId: '942040795881-c54og28abm4vr5stfe7mui9vsc9ufpqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.legaleasier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ZMKU-S-H0cUeyyTja86cBaVHKdoxlFU',
    appId: '1:942040795881:web:b81d9ba8b5d4aec3edbe78',
    messagingSenderId: '942040795881',
    projectId: 'legaleasier-15871',
    authDomain: 'legaleasier-15871.firebaseapp.com',
    storageBucket: 'legaleasier-15871.firebasestorage.app',
  );
}
